from django.conf.urls import url
from . import views
urlpatterns = [
        url(r'^$',views.main,name='main'),
        url(r'^aboutus/$',views.aboutus,name='aboutus'),
        url(r'^commonlogin/$',views.commonlogin,name='commonlogin'),
        url(r'^studentregister/$',views.studentregister,name='studentregister'),
        url(r'^studentregister/questionnaire/$',views.showquestionnaire,name='studentquestions'),
        url(r'^studentregister/questionnaire/submit$',views.questionnaire,name='submitstudentquestions'),
        url(r'^collegeregister/$',views.collegeregister,name='collegeregister'),
		url(r'^studentdashboard/$',views.new_student,name='studentsubmit'),
		url(r'^collegedashboard/$',views.new_college,name='collegesubmit'),
		url(r'^student_dashboard/$',views.stddash,name='studentdashboard'),
		url(r'^college_dashboard/$',views.clgdash,name='collegedashboard'),
		url(r'^student_dashboard/changemail/$',views.changemail,name="changemail"),
		url(r'^student_dashboard/changename/$',views.changename,name="changename"),
		url(r'^student_dashboard/changephone/$',views.changephone,name="changephone"),
		url(r'^student_dashboard/changeadd/$',views.changeadd,name="changeadd"),
		url(r'^student_dashboard/changepass/$',views.changepass,name="changepass"),
		url(r'^college_dashboard/changemail/$',views.changecollegemail,name="changecollegemail"),
		url(r'^college_dashboard/changepass/$',views.changeclgpass,name="changecollegepass"),
		url(r'^college_dashboard/changename/$',views.changeclgname,name="changecollegename"),
		url(r'^college_dashboard/changephone/$',views.changeclgphone,name="changecollegephone"),
		url(r'^college_dashboard/changeadd/$',views.changeclgadd,name="changecollegeaddress"),
		url(r'^college_dashboard/changeyear/$',views.changeclgyear,name="changecollegeyear"),
		url(r'^college_dashboard/changedir/$',views.changeclgdir,name="changecollegedirector"),
		url(r'^college_dashboard/passauth/$',views.passauth,name="passwordauthentication"),
		url(r'^College_dashboard/$',views.search,name="searchupdate"),
		url(r'^college_dashboard/pairings/$',views.pair,name="showpairing"),
		url(r'^college_dashboard/pairedlist/$',views.download,name="downloadpairing"),
]	
